"""
tools/analyze_spreadsheet.py
=============================
AnalyzeSpreadsheetTool — read and summarize an uploaded .xlsx/.xls/.csv file.

This is a READ-AND-SUMMARIZE tool.  It is the OPPOSITE data-flow direction of
GenerateXlsxTool (which writes files) — do not confuse the two.

Data flow
---------
1. Extract structure from the file using openpyxl (already a project dep).
   For .csv files, a thin CSV-reader is used (stdlib csv module, no pandas).
2. Build a structured JSON-serialisable extract: sheet names, row/col counts,
   column headers, numeric column stats (min / max / mean).
3. Send the structured extract to the reasoning LLM — the model summarises
   the EXTRACT, never sees the raw file bytes.
4. Return both the structured extract and the natural-language summary.

Sovereignty / dependency note
------------------------------
Uses only openpyxl and stdlib csv — both already present.  No pandas,
no external network calls, no new dependencies added.

Input schema
------------
file_path  : str  — absolute path to the uploaded .xlsx / .xls / .csv
request_id : str  — correlation ID for audit logging

Output
------
ToolResult.output   : {
    "sheets": [
        {
            "name": str,
            "row_count": int,
            "col_count": int,
            "headers": [str, ...],
            "rows": [                        # NEW: actual data rows (up to 100)
                {"<header>": <value>, ...},  #      list of header→value dicts
                ...
            ],
            "numeric_stats": {
                "<col_header>": {"min": float, "max": float, "mean": float},
                ...
            }
        },
        ...
    ],
    "summary": str   # natural-language summary from the LLM
}
ToolResult.metadata : {
    "filename": str,
    "sheet_count": int,
    "total_rows": int
}

Audit
-----
One TOOL_CALL record per call: request_id, filename, sheet_count, total_rows.
"""

from __future__ import annotations

import csv
import io
import json
import logging
import time
from pathlib import Path
from typing import Any, Optional, Protocol, runtime_checkable

from app.audit.logger import AuditLogger, EventType
from app.tools.base import BaseTool, ToolResult

_log = logging.getLogger("sovereign.tools.analyze_spreadsheet")

_SUMMARY_SYSTEM_PROMPT = """\
You are a data analyst assistant. Given a structured extract of a spreadsheet file
(including actual row data and numeric statistics), produce a concise 2–4 sentence
natural-language summary that describes:
- What the spreadsheet appears to contain (subject matter / domain)
- How many sheets and rows of data it has
- Key line items, totals, or amounts visible in the row data
- Any notable patterns, ranges, or outliers visible in the numeric stats

Be factual and specific. Mention actual values from the rows where relevant.
Do not invent data not present in the extract.\
"""


# ---------------------------------------------------------------------------
# LLM protocol (same shape as OllamaClient.chat_completion)
# ---------------------------------------------------------------------------


@runtime_checkable
class LLMAnalysisProtocol(Protocol):
    async def chat_completion(
        self,
        messages: list[dict[str, str]],
        *,
        request_id: Optional[str] = None,
        temperature: float = ...,
        max_tokens: int = ...,
        extra_body: Optional[dict[str, Any]] = None,
    ) -> Any:
        """Must return an object with a ``.content: str`` attribute."""
        ...


# ---------------------------------------------------------------------------
# Tool
# ---------------------------------------------------------------------------


class AnalyzeSpreadsheetTool(BaseTool):
    """
    Read and summarize an uploaded .xlsx / .xls / .csv file.

    Returns structured extraction (sheet names, row/col counts, headers,
    numeric stats) plus a natural-language summary generated by the LLM
    from that structured extract — the model never sees the raw file.
    """

    name = "analyze_spreadsheet"
    description = (
        "Read and summarize an uploaded .xlsx, .xls, or .csv file. "
        "Returns structured data (sheet names, row/column counts, column headers, "
        "numeric stats) and a natural-language summary. "
        "Use this when the user wants to understand or summarize a spreadsheet — "
        "NOT for generating a new spreadsheet (use generate_xlsx for that)."
    )
    input_schema = {
        "type": "object",
        "properties": {
            "file_path": {
                "type": "string",
                "description": "Absolute path to the uploaded .xlsx, .xls, or .csv file.",
            },
            "request_id": {
                "type": "string",
                "description": "Correlation ID propagated through the audit log.",
            },
        },
        "required": ["file_path"],
    }

    def __init__(
        self,
        llm_client: LLMAnalysisProtocol,
        audit_logger: Optional[AuditLogger] = None,
    ) -> None:
        self._llm = llm_client
        self._audit = audit_logger

    async def execute(self, **kwargs: Any) -> ToolResult:
        file_path: Optional[str] = kwargs.get("file_path")
        request_id: Optional[str] = kwargs.get("request_id")

        if not file_path:
            return ToolResult(success=False, output=None,
                              error="Missing required argument: file_path")

        path = Path(file_path)
        if not path.exists():
            return ToolResult(success=False, output=None,
                              error=f"File not found: {file_path}")

        ext = path.suffix.lower()
        if ext not in {".xlsx", ".xls", ".csv"}:
            return ToolResult(success=False, output=None,
                              error=f"Unsupported file type: '{ext}'. "
                                    "Supported: .xlsx, .xls, .csv")

        t0 = time.monotonic()
        try:
            if ext == ".csv":
                sheets_extract = self._extract_csv(path)
            else:
                sheets_extract = self._extract_xlsx(path)
        except Exception as exc:
            _log.exception("Spreadsheet extraction failed: %s", file_path)
            return ToolResult(success=False, output=None,
                              error=f"Extraction failed: {exc}")

        total_rows = sum(s["row_count"] for s in sheets_extract)
        sheet_count = len(sheets_extract)

        # Build summary via LLM — from structured extract, not raw file
        extract_text = json.dumps(sheets_extract, indent=2, ensure_ascii=False)
        summary = await self._summarise(extract_text, request_id=request_id)

        elapsed_ms = (time.monotonic() - t0) * 1000

        self._log_call(
            filename=path.name,
            sheet_count=sheet_count,
            total_rows=total_rows,
            duration_ms=elapsed_ms,
            request_id=request_id,
        )

        return ToolResult(
            success=True,
            output={
                "sheets": sheets_extract,
                "summary": summary,
            },
            metadata={
                "filename": path.name,
                "sheet_count": sheet_count,
                "total_rows": total_rows,
            },
        )

    # ------------------------------------------------------------------
    # Extraction — xlsx / xls
    # ------------------------------------------------------------------

    # Maximum rows included in the structured extract (per sheet).
    # Enough for any real budget/report sheet; prevents huge payloads.
    _MAX_ROWS = 100

    def _extract_xlsx(self, path: Path) -> list[dict[str, Any]]:
        """Extract structure from an .xlsx/.xls file using openpyxl.

        Each sheet dict now includes a ``rows`` key containing up to
        ``_MAX_ROWS`` data rows as list-of-dicts ({header: value}).  This
        is the fix for Bug A: previously only aggregated stats were included
        and actual line-item data was silently discarded.
        """
        import openpyxl

        wb = openpyxl.load_workbook(str(path), read_only=True, data_only=True)
        sheets: list[dict[str, Any]] = []

        for sheet_name in wb.sheetnames:
            ws = wb[sheet_name]
            rows_iter = list(ws.iter_rows(values_only=True))
            if not rows_iter:
                sheets.append({
                    "name": sheet_name,
                    "row_count": 0,
                    "col_count": 0,
                    "headers": [],
                    "rows": [],
                    "numeric_stats": {},
                })
                continue

            # First row as headers; remaining rows as data
            raw_headers = rows_iter[0]
            headers = [str(h) if h is not None else f"Col{i+1}"
                       for i, h in enumerate(raw_headers)]
            data_rows = rows_iter[1:]

            row_count = len(data_rows)
            col_count = len(headers)
            numeric_stats = _compute_numeric_stats(headers, data_rows)

            # ── NEW: include actual row data (up to _MAX_ROWS) ──────────
            # Convert each row to a {header: value} dict.  None cells are
            # preserved as None so the LLM can distinguish missing values.
            sampled_rows: list[dict[str, Any]] = []
            for raw_row in data_rows[:self._MAX_ROWS]:
                row_dict = {}
                for i, header in enumerate(headers):
                    cell_val = raw_row[i] if i < len(raw_row) else None
                    row_dict[header] = cell_val
                sampled_rows.append(row_dict)

            _log.info(
                "[SPREADSHEET EXTRACT] sheet=%r  rows=%d  cols=%d  sampled=%d  "
                "first_row=%s",
                sheet_name, row_count, col_count, len(sampled_rows),
                sampled_rows[0] if sampled_rows else "(empty)",
            )

            sheets.append({
                "name": sheet_name,
                "row_count": row_count,
                "col_count": col_count,
                "headers": headers,
                "rows": sampled_rows,          # ← NEW: actual line-item data
                "numeric_stats": numeric_stats,
            })

        wb.close()
        return sheets

    # ------------------------------------------------------------------
    # Extraction — csv
    # ------------------------------------------------------------------

    def _extract_csv(self, path: Path) -> list[dict[str, Any]]:
        """Extract structure from a .csv file using stdlib csv module.

        Includes ``rows`` key (up to ``_MAX_ROWS``) for the same reason as
        ``_extract_xlsx`` — so downstream steps see actual cell values.
        """
        rows: list[tuple] = []
        try:
            with path.open(newline="", encoding="utf-8-sig") as fh:
                reader = csv.reader(fh)
                for row in reader:
                    rows.append(tuple(row))
        except UnicodeDecodeError:
            # Fallback to latin-1 if UTF-8 fails
            with path.open(newline="", encoding="latin-1") as fh:
                reader = csv.reader(fh)
                for row in reader:
                    rows.append(tuple(row))

        if not rows:
            return [{"name": path.stem, "row_count": 0, "col_count": 0,
                     "headers": [], "rows": [], "numeric_stats": {}}]

        raw_headers = rows[0]
        headers = [str(h) if h else f"Col{i+1}" for i, h in enumerate(raw_headers)]
        data_rows = rows[1:]
        row_count = len(data_rows)
        col_count = len(headers)
        numeric_stats = _compute_numeric_stats(headers, data_rows)

        # ── NEW: actual row data (up to _MAX_ROWS) ─────────────────────
        sampled_rows: list[dict[str, Any]] = [
            {headers[i]: (row[i] if i < len(row) else None)
             for i in range(len(headers))}
            for row in data_rows[:self._MAX_ROWS]
        ]

        _log.info(
            "[SPREADSHEET EXTRACT] csv=%r  rows=%d  cols=%d  sampled=%d  "
            "first_row=%s",
            path.name, row_count, col_count, len(sampled_rows),
            sampled_rows[0] if sampled_rows else "(empty)",
        )

        return [{
            "name": path.stem,
            "row_count": row_count,
            "col_count": col_count,
            "headers": headers,
            "rows": sampled_rows,           # ← NEW
            "numeric_stats": numeric_stats,
        }]

    # ------------------------------------------------------------------
    # LLM summarisation
    # ------------------------------------------------------------------

    async def _summarise(self, extract_json: str, *, request_id: Optional[str]) -> str:
        """Send the structured extract to the LLM and return the summary text."""
        messages = [
            {"role": "system", "content": _SUMMARY_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    "Here is the structured extract from the spreadsheet:\n\n"
                    f"```json\n{extract_json}\n```\n\n"
                    "Please provide a concise summary."
                ),
            },
        ]
        try:
            resp = await self._llm.chat_completion(
                messages,
                request_id=request_id,
                temperature=0.2,
                max_tokens=512,
            )
            return resp.content
        except Exception as exc:
            _log.warning("LLM summarisation failed: %s", exc)
            return f"(Summarisation unavailable: {exc})"

    # ------------------------------------------------------------------
    # Audit
    # ------------------------------------------------------------------

    def _log_call(
        self,
        filename: str,
        sheet_count: int,
        total_rows: int,
        duration_ms: float,
        request_id: Optional[str],
    ) -> None:
        if not self._audit:
            return
        try:
            self._audit.log_event(
                event_type=EventType.TOOL_CALL,
                request_id=request_id or "",
                payload={
                    "tool": "analyze_spreadsheet",
                    "filename": filename,
                    "sheet_count": sheet_count,
                    "total_rows": total_rows,
                    "duration_ms": round(duration_ms, 1),
                },
            )
        except Exception as exc:
            _log.warning("Failed to write audit record: %s", exc)


# ---------------------------------------------------------------------------
# Pure numeric stats helper
# ---------------------------------------------------------------------------


def _compute_numeric_stats(
    headers: list[str],
    data_rows: list[tuple],
) -> dict[str, dict[str, float]]:
    """
    Compute min/max/mean for each column that contains numeric values.

    Skips columns where fewer than 2 values are numeric.
    Returns a dict: column_header → {min, max, mean}.
    """
    stats: dict[str, dict[str, float]] = {}
    col_count = len(headers)

    for col_idx, header in enumerate(headers):
        values: list[float] = []
        for row in data_rows:
            if col_idx >= len(row):
                continue
            cell = row[col_idx]
            if cell is None:
                continue
            if isinstance(cell, (int, float)):
                values.append(float(cell))
            else:
                try:
                    values.append(float(str(cell).replace(",", "")))
                except (ValueError, TypeError):
                    pass

        if len(values) >= 2:
            stats[header] = {
                "min": round(min(values), 4),
                "max": round(max(values), 4),
                "mean": round(sum(values) / len(values), 4),
            }

    return stats
